### PR TITLE
Quark TCK/RI for reactive sockets

### PR DESCRIPTION
**Pull request by rhs**
This pull request comes out of a series of conversations between @benjchristensen and myself about the possibility of using a language like Quark to help bootstrap protocol implementations like reactive sockets. Please see the README.md that is part of the pull request for more detailed info.

### CODE REVIEW

**Comment by stevegury** [comment]
I don't know if `reactivesocket` is the right repo for this, maybe we should create a repo called `reactivesocket-tck` ?
What others think?

**Comment by benjchristensen** [comment]
I had suggested this location so compliance tests lived with the specification.

**Comment by benjchristensen** [comment]
I think it would be best in a folder /tck/

**Comment by rhs** [comment]
I just simplified the install instructions and moved the whole thing into the tck folder as suggested.

**Comment by benjchristensen** [comment]
@rhs Got the code checked out, compiled the quark files, trying to run tests now, but getting this:

```
:tck benjchristensen$ quark run rxtest.q --python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named rxtest
:tck benjchristensen$ ls rxtest.q
rxtest.q
```

**Comment by rhs** [comment]
Hi Ben,

Did you run "quark compilie" or "quark install"? For "quark run" to work you need to do "quark install". The "quark compile" command just produces source code and leaves you to build/install it on your own, e.g. with pip in the case of python.

**Comment by benjchristensen** [comment]
I installed quark (and pip to do that). Then I did "quark compile" and it finishes. I didn't realize I had to run "quark install" as well before being able to run. 

```
$ quark compile rxtest.q rxclient.q rxserver.q
Checking environment ... done.
Parsing: rxtest.q ....
Compiling quark code ..............................................................................................................................................................................................
Parsing: rxclient.q ...
Compiling quark code .............................................................................................................................................................................................
Parsing: rxserver.q ....
Compiling quark code ..............................................................................................................................................................................................
Done
```

When I try "install" I get a different error:

```
$ quark install rxtest.q rxclient.q rxserver.q --python
Checking environment ....

unable to find required python package wheel
```

So ...

```
$ sudo pip install wheel
```

Then "install" works:

```
$ quark install rxtest.q rxclient.q rxserver.q --python
Checking environment ....
Parsing: rxtest.q ...
Compiling quark code .........
Installing Python quark with PIP .......
Installing Python rxlib with PIP .......
Installing Python rxtest with PIP ....
Parsing: rxclient.q ....
Compiling quark code ........
Installing Python quark with PIP .......
Installing Python rxlib with PIP .......
Installing Python rxclient with PIP .....
Parsing: rxserver.q ...
Compiling quark code .........
Installing Python quark with PIP .......
Installing Python rxlib with PIP .......
Installing Python rxserver with PIP ....
Done
```

It now works:

```
$ quark run rxtest.q --python
Running: rxtest
=============================== starting tests ===============================
rxtest.RoundTripTest.testSetup1 [5 checks, 0 failures]
rxtest.RoundTripTest.testSetup2 [5 checks, 0 failures]
rxtest.RoundTripTest.testLease1 [2 checks, 0 failures]
rxtest.RoundTripTest.testLease2 [2 checks, 0 failures]
rxtest.RoundTripTest.testLease3 [2 checks, 0 failures]
rxtest.RoundTripTest.testLease4 [2 checks, 0 failures]
=============================== stopping tests ===============================
Total: 6, Filtered: 0, Passed: 6, Failed: 0
```

So one must do "compile", "install", then "run" each time a file is changed?

**Comment by rhs** [comment]
It actually isn't necessary to do compile at all unless you want to view the generated source code. You can just do 'quark install blah.q', and that will detect any changes in your .q file or in any .q files that it depends on and perform an incremental rebuild.

I can see the README is probably a little confusing on this point. I am going to be hopping on a plane soon, but I will update the README to be more clear. Basically the only reason to use quark compile is if you want access to the intermediate artifacts that quark install creates, e.g. say you wanted to push the generated java code up to maven central or something like that.

I will also update our environment checks so you get a more useful error message when the wheel package is missing, and add a check that the code is installed before trying to run it.

**Comment by benjchristensen** [comment]
Thanks @rhs

**Comment by benjchristensen** [comment]
@ReactiveSocket/reactivesocketprotocol I propose merging this so we can start iterating.

**Comment by stevegury** [comment]
I ran into the exact same problem as Ben while testing.
@rhs I propose to move your comment into the README, I suppose most users will not be familiar with quark, they will need a little bit of help to setup the project.

**Comment by rhs** [comment]
I added the language from my comment into the README as @stevegury suggested.

**Comment by benjchristensen** [comment]
Steve, shall we merge and start submitting PRs to iterate?

**Comment by stevegury** [comment]
👍

**Pull request merged**
