### PR TITLE
Frame Type from 8 to 6 bits to increase Flags

### PR DESCRIPTION
**Pull request by benjchristensen**
Move 2 bits from Frame Type to Flags.

Discussions have led to the conclusion that we don't need more that 2^6 (64) frame types, but want to grant more room for future additions of flags.

### CODE REVIEW

**Comment by tmontgomery** [comment]
EXT should be 0x3F (all 1s).

**Comment by benjchristensen** [comment]
Right you are.

**Comment by benjchristensen** [comment]
@NiteshKant and @stevegury Are you okay with this change?

**Comment by benjchristensen** [comment]
Thanks for the review and "heart" @robertroeser Will merge since we have approval from @tmontgomery @robertroeser and Vijayan and myself.

**Pull request merged**
